### PR TITLE
fix for new reddit layout

### PR DESCRIPTION
**Pull request by kufii**
title says it all. The extension is currently broken on the new reddit layout and this fixes it

### CODE REVIEW

**Comment by constantinedc** [comment]
Thanks for doing this! I wasn't even aware there was an issue. I'll try and have a look tonight.

**Comment by constantinedc** [comment]
Hi Kufii!

Sorry it took me a while to get to this. There's at least one thing that seems to be broken in new reddit but works in old reddit:

https://www.reddit.com/r/testingbetazoidberg/comments/3egsup/spike_der_spiegel_test/

Other than that, everything looks great. I'll be pretty busy for the next few days but I'll try and have a look into it some time next week if you haven't gotten to it by then. 

Thanks again!

**Comment by kufii** [comment]
Good catch, it was because new reddit was turning the "r/" into a subreddit link. Fixed

**Comment by constantinedc** [comment]
Yep, looks like that was it. Two things I noticed:

1. The header section is no longer bold. It looks like new reddit disables the font-weight. I'll just make a new issue for this after this PR goes through since that's more a styling thing than functionality anyway.

2. Can we just use a non greedy `.` for catching the class attributes in the ol/li elements?
`<ol.*?>` 
seems to catch
`<ol class="s570a4-13 hPDIiA">`
just fine. 
I did a check of a couple of examples in r/testingbetazoidberg and it seems to work and looks cleaner. Was there a particular scenario you found where that wouldn't work?

Thanks!

**Comment by kufii** [comment]
yeah we could do that, I initially did it the other way in case of potential conflicts, for example if reddit started using custom tags that happened to start with ol, but honestly that's so unlikely that you're right, I can just use .*

**Comment by kufii** [comment]
EDIT:

Misunderstood what you were saying `.*?` works. Cool trick, didn't actually know you could do that with regex

**Comment by constantinedc** [comment]
Finally managed to find time to get back to this - looks great! I'll complete this pr and then try and find time at some point this week to release the changes from this and #21 to a new version.

Thanks again.

**Comment by kufii** [comment]
awesome! mind letting me know when it's been pushed to the chrome store?

**Comment by constantinedc** [comment]
All done! Please lemme know if you notice any issues. Thanks again for doing this - I've credited you as kufii on the changelog, but if you want me to put something else instead just mention it. 

As an aside, I'm going to try to contact the r/chess mod team to see if there's some way they can take ownership of the extension and take care of merging/publishing changes since I'm no longer active enough on reddit to be aware of when changes like this are needed. I'll always be happy to lend a hand but if they take over they might be the more appropriate first contact in the future.

**Pull request merged**
